### ISSUE TITLE
Internal Error when requesting SSL certificate

### ISSUE THREAD

**Issue by JCoupalK** [openappsec/open-appsec-npm#10]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes / **No**
- Are you sure you're not using someone else's docker image?
  - **Yes** / No
- Have you searched for similar issues (both open and closed)?
  - **Yes** / No

**Describe the bug**
I get an internal error when I try to add a SSL certificate on a proxy but it still creates the proxy on an "Unknown" status when I refresh and without the certificate previously created and I can't seem to add it back.

This issue does not arise on a normal Nginx Proxy Manager image.

**Nginx Proxy Manager Version**
v1.0.0-beta.1

**To Reproduce**
1. Go to 'Add Proxy Host'
2. Fill out the informations for a proxy
3. Request an SSL certificate
4. Enable open-appsec
5. Save
6. It should give you an internal error

**Expected behavior**
Should just give you the certificate and deploy it with a normal status.

**Screenshots**
The error:
![image](https://github.com/openappsec/open-appsec-npm/assets/108779415/1b5b808a-0c65-40e9-b2f2-c7a73731ee9b)

What I see when I refresh despite the error:
![image](https://github.com/openappsec/open-appsec-npm/assets/108779415/d503031c-6528-407f-9fc5-b752ec16f591)

When I try to add the certificate back I just get a red bar:
![image](https://github.com/openappsec/open-appsec-npm/assets/108779415/d17237be-c011-4fda-b45f-d684c1d02f2f)

**Operating System**
Tested on AlmaLinux 9.2 and Ubuntu 22.04 using Docker.

**Comment by freeoneed** [comment]
Yes, but the certificate is being created. Check the SSL tab. If the certificate is there, then you can apply it on the main tab. This way you can work around this bug while it is being fixed.

**Comment by orianelou** [comment]
Hi, 

@freeoneed , Thank you for the work around and supporting our community!
@JCoupalK we're looking into this and we'll update. 

Best,

open-apspec team

**Comment by mgrimace** [comment]
> Yes, but the certificate is being created. Check the SSL tab. If the certificate is there, then you can apply it on the main tab. This way you can work around this bug while it is being fixed.

The certificate is not being created in my case, even if I exit out, refresh, etc.

**Comment by orianelou** [comment]
Hi @mgrimace, 

Have you used the same flow described above? 

Thanks!

**Comment by mgrimace** [comment]
> Hi @mgrimace,
> 
> Have you used the same flow described above?
> 
> Thanks!

Yes, I used the exact flow above with one exception: I selected request a new certificate with Let's Encrypt + `use a DNS challenge` and selected Cloudflare. My use-case was to create a local service with SSL `service.local.mydomain.com` whereas other services exposed to the internet use my existing cloudflare certificate.

I also tried creating a new SSL dns challenge certificate directly in the SSL tab and also had th same `internal error` behaviour. My workaround was to stop/remove the docker npm+appsec container, spin up the old regular npm container, create the certificates, then back to npm+appsec.

**Comment by freeoneed** [comment]
In my case, a simple subdomain was used

**Comment by JCoupalK** [comment]
Any update concerning the issue?

Thank you

**Comment by orianelou** [comment]
Hi all, 

We've identified the issue and we'll publish a new version with the fix soon.

Thank you for your involvement!

**Comment by JCoupalK** [comment]
Hi,

Would you have an ETA for the fix?

Thank you

**Comment by orianelou** [comment]
Hi, 

The issue was resolved, please update to the latest [NGINX Proxy Manager attachment container](https://github.com/orgs/openappsec/packages/container/package/nginx-proxy-manager-attachment) 

I appreciate your patience and involvement!
