### ISSUE TITLE
Crowdsec integration

### ISSUE THREAD

**Issue by zichichi** [openappsec/open-appsec-npm#14]
Would it be possible to integrate crowdsec as indicated here?
https://www.openappsec.io/post/open-appsec-introduces-crowdsec-integration-for-community-threat-intelligence-protection

**Comment by orianelou** [comment]
Hi @zichichi, 

It is possible, you can example from our community here https://github.com/openappsec/openappsec/issues/133, we're looking into they issue the mentioned and we'll update there (closing this issue for now)
