### ISSUE TITLE
Openappsec NPM wont send logs to SIEM

### ISSUE THREAD

**Issue by tltglitch** [openappsec/open-appsec-npm#17]
I used the documentation :
https://docs.openappsec.io/getting-started/start-with-linux/local-policy-file-advanced

However i cannot get openappsec to send logs to siem in this case splunk. I checked firewall traffic and nothing is being generated by crowdsec or sent over the network over port 514. Firewall ports are open and other devices are sending to SIEM

Here i s my default log trigger config:

log-triggers:
  - name: appsec-default-log-trigger
    access-control-logging:
      allow-events: false
      drop-events: true
    additional-suspicious-events-logging:
      enabled: true
      minimum-severity: high
      response-body: false
      response-code: true
    appsec-logging:
      all-web-requests: false
      detect-events: true
      prevent-events: true
    extended-logging:
      http-headers: false
      request-body: false
      url-path: true
      url-query: true
    log-destination:
      cloud: false
      stdout:
        format: json
      syslog-service:
        - address: <splunk address>
          port: 514

**Comment by orianelou** [comment]
Hi @tltglitch, 

It seems the log trigger isn't defined correctly, see an example, in the address you should configure the syslog server IP address 
![image](https://github.com/openappsec/open-appsec-npm/assets/126462046/68d6b1f3-db71-493d-be7a-d193ce274833)

**Comment by tltglitch** [comment]
Well the address is empty because i removed it not to show on github but i do have an ip address in the log trigger.
