### ISSUE TITLE
Openappsec track learning 

### ISSUE THREAD

**Issue by tltglitch** [openappsec/open-appsec-npm#18]
As per the documentation:

https://docs.openappsec.io/how-to/track-learning-and-move-from-learn-detect-to-prevent

Is there a way to track learning using NPM localy hosted using the CLI? or open-app-secctl tool?

**Comment by git-SwitchBlade** [comment]
Let me know if you find the solution, cause the model in detect-learn generates to many false positives.

**Comment by orianelou** [comment]
Hi @git-SwitchBlade, 

We've released this feature in beta, please note that provided docker compose would be need slightly adjusted to support NPM https://docs.openappsec.io/how-to/track-learning-and-local-tuning-in-standalone-deployments 

let us know what you think!
