### ISSUE TITLE
Failed checkpoint update request

### ISSUE THREAD

**Issue by izaias-cunha** [openappsec/open-appsec-npm#21]
Every 5 minutes I get the following error in the logs. Is this a configuration issue that I overlooked?

},
  "eventData": {
    "logIndex": 7,
    "eventMessage": "Updates process reports:\n[2024-07-13T21:40:50.769381] - FAILURE | GENERAL | GET_UPDATE_REQUEST | Failed to get update request. Error: Warning: Agent/Gateway failed during the update process. Contact Check Point support.\n[2024-07-13T21:40:50.769806] - FAILURE | GENERAL | CHECK_UPDATE | Failed during check update. Error: Failed to establish connection. Error: inext-agents.cloud.ngen.checkpoint.com:443. There won't be a retry attempt.\n"
  }
}

**Comment by orianelou** [comment]
Hi @izaias-cunha, 

Can you please verify that you've allowed connection to our fog, you can read more here https://docs.openappsec.io/concepts/agents#secure-communication
