### ISSUE TITLE
problem with load policy

### ISSUE THREAD

**Issue by lajooie** [openappsec/open-appsec-npm#29]
hi guys 
I have a problem that you can see in the following post  with load policy
Can someone tell me the solution?
tnx

---- open-appsec Nano Agent ----
Version: 1.1.18-open-source
Status: Running
AI model version: Simple model V1.0
Management mode: Local management
Agent ID:
Policy files:
    /etc/cp/conf/local_policy.yaml
Policy load status: Error
Last policy update: None

**Comment by orianelou** [comment]
Hi @lajooie, 

Can you please verify the open-appsec agent has access to our fog at 

- https://inext-agents.cloud.ngen.checkpoint.com
- https://downloads.openappsec.io

If this doesn't solve the issue could you please send us the compose file used?

best, 

The open-appsec team

**Comment by lajooie** [comment]
tanks @orianelou,
my problem  solved

**Comment by orianelou** [comment]
Hi, 

This is currently not supported, you're welcome to send an email to info@openappsec.io with your details and we'll reach out if this feature is added.
