### ISSUE TITLE
In the absence of a proxy host and a network connection, the CPU load rate remains high, and logs are continuously output with repeated errors, resulting in more than 2G of log files every day.

### ISSUE THREAD

**Issue by Jiejd** [openappsec/open-appsec-npm#30]
Installation environment: docker

The log records are repeated as follows:⬇️
 tail: cannot open '/var/log/nano_agent/cp-nano-http-transaction-handler.log?' for reading: No such file or directory
tail: no files remaining.

**Comment by Jiejd** [comment]
Deployment steps: mkdir ./appsec-localconfig
, wget
https://raw.githubusercontent.com/openappsec/open-appsec-npm/main/deployment/local_policy.yaml -O ./appsec-localconfig/local_policy.yaml, 
wget https://raw.githubusercontent.com/openappsec/open-appsec-npm/main/deployment/docker-compose.yaml, docker-compose up -d

**Comment by Jiejd** [comment]
Deployment steps: 
mkdir ./appsec-localconfig
 wget https://raw.githubusercontent.com/openappsec/open-appsec-npm/main/deployment/local_policy.yaml -O ./appsec-localconfig/local_policy.yaml
 wget https://raw.githubusercontent.com/openappsec/open-appsec-npm/main/deployment/docker-compose.yaml
docker-compose up -d

**Comment by orianelou** [comment]
Hi @Jiejd 

We're aware of the issue and are working on solving it. As a work around you can:

Delete the file:
Add a file named: /var/log/nano_agent/cp-nano-http-transaction-handler.log1
Thank you for reporting this, and my apologies for the inconvenience.

The open-appsec team

**Comment by Jiejd** [comment]
@orianelou Thanks for your reply, the problem was solved after adding the file.

**Comment by orianelou** [comment]
Hi, issue was solved in latest agent release
