### ISSUE TITLE
Compatibility with Centrally Managed open-appsec

### ISSUE THREAD

**Issue by gallart** [openappsec/open-appsec-npm#6]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes
  - 
**Describe the bug**
Trying to figure out how to deploy open-appsec-npm with Centrally Managed open-appsec container.

**Nginx Proxy Manager Version**
1.0.0-beta1

**To Reproduce**
1. Deploy npm
2. Have it communicate with existing open-appsec

**Expected behavior**
Either suggest other docker-compose with working open-appsec with central management.
Either explain a way for nginx/npm to communicate with existing open-appsec.

**Operating System**
Docker

**Comment by orianelou** [comment]
Hi @gallart, 

We're working on a container that will allow connection to open-appsec UI, and hope to have it released soon. 

Could you please let us know which part of the open-appsec UI are you missing in the Enhanced NGINX Proxy Manager UI we have published? Your feedback is valuable to us and will allow us to better plan our next steps.

Thank you!

**Comment by gallart** [comment]
Hi,

I have finally been able to get a properly running setup with this docker-compose file :

```
version: '3.3'
# docker compose for npm open-appsec integration

services:
  appsec-npm:
    container_name: npm-attachment
    image: 'ghcr.io/openappsec/nginx-proxy-manager-attachment:latest'
    ipc: host
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./appsec-logs:/ext/appsec-logs
      - ./appsec-localconfig:/ext/appsec

  appsec-agent:
    container_name: appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    network_mode: service:appsec-npm
    ipc: host
    restart: unless-stopped
    environment:
      # adjust with your own email below
      - user_email=gaetan@nexylan.com
      - nginxproxymanager=true
      - autoPolicyLoad=true
    volumes:
      - /etc/appsec/conf:/etc/cp/conf
      - /etc/appsec/data:/etc/cp/data
      - /etc/appsec/logs:/var/log/nano_agent
      - /etc/appsec/advanced-model/open-appsec-advanced-model.tgz:/advanced-model/open-appsec-advanced-model.tgz:rw
      #- ./appsec-localconfig:/ext/appsec
    command: /cp-nano-agent --token xxxxxxxxxxx
```
